# Generated by Django 4.2 on 2023-12-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Matric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date_of_birth", models.CharField(max_length=100)),
                ("student_name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100, null=True)),
                ("email_address", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("phone_number", models.TextField(blank=True, null=True)),
                ("board", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "total_marks",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "obtained_marks",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("percentage", models.CharField(blank=True, max_length=100, null=True)),
                ("roll_no", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
