# Generated by Django 4.2 on 2023-12-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OCRAPP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matric",
            name="fsc_board",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="matric",
            name="fsc_obtained_marks",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="matric",
            name="fsc_percentage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="matric",
            name="fsc_roll_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="matric",
            name="fsc_total_marks",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matric",
            name="roll_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
