# Generated by Django 4.2.10 on 2024-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCRAPP', '0002_matric_fsc_board_matric_fsc_obtained_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matric',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
